USE ROLE USERADMIN;

CREATE ROLE DATA_LOADER;
CREATE ROLE DATA_ENGINEER;
CREATE ROLE DATA_ANALYST;

-- Data Loader Privileges
GRANT USAGE ON WAREHOUSE DW_RAW TO ROLE DATA_LOADER;
GRANT USAGE ON DATABASE EDW_SANTEX TO ROLE DATA_LOADER;
GRANT CREATE STAGE ON SCHEMA EDW_SANTEX.RAW TO ROLE DATA_LOADER; -- For loading from external stages
GRANT SELECT, INSERT, UPDATE ON SCHEMA EDW_SANTEX.RAW TO ROLE DATA_LOADER;

-- Data Engineer Privileges
GRANT USAGE ON WAREHOUSE DW_STAGE TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE EDW_SANTEX TO ROLE DATA_ENGINEER;
GRANT USAGE ON ALL STAGES IN SCHEMA EDW_SANTEX.RAW TO ROLE DATA_ENGINEER; -- Access to external stages
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA EDW_SANTEX.RAW TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA EDW_SANTEX.STAGE TO ROLE DATA_ENGINEER;

-- Data Analyst Privileges
GRANT USAGE ON WAREHOUSE DW_PROD TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE EDW_SANTEX TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA EDW_SANTEX.PROD TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA EDW_SANTEX.PROD TO ROLE DATA_ANALYST;
