CREATE OR REPLACE STORAGE INTEGRATION S3_RAW_DATA
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::*********:role/raw-s3-integration'
  STORAGE_ALLOWED_LOCATIONS = ('s3://raw/snowpipe_data/');


  CREATE OR REPLACE STAGE RAW_S3_STAGE
  URL = 's3://raw/snowpipe_data/'
  STORAGE_INTEGRATION = S3_RAW_DATA; 


  CREATE PIPE RAW_SNOWPIPE_CUSTOMER_SEGMENTATION_DATA AUTO_INGEST = TRUE AS
    COPY INTO CUSTOMER_SEGMENTATION_DATA
    FROM @RAW_S3_STAGE
    FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT); 

CREATE OR REPLACE STORAGE INTEGRATION S3_PROD_DATA
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::*********:role/prod-s3-integration'
  STORAGE_ALLOWED_LOCATIONS = ('s3://Prod/EDW/');